myapp/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home_page, name="home"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.signup, name="login"),
    path("account/", views.account, name="account"),
    path("add_equipment/", views.add_equipment, name="add_equipment"),
    path("all_equipment/", views.all_equipment, name="all_equipment"),
    path("equipment_on_mission/", views.equipment_on_mission, name="equipment_on_mission"),
    path("equipment_on_maintenance/", views.equipment_on_maintenance, name="equipment_on_maintenance"),
    path("damaged_equipment/", views.damaged_equipment, name="damaged_equipment"),
    path("deploy_equipment_on_mission/<int:equipment_id>/", views.deploy_equipment_on_mission, name="deploy_equipment_on_mission"),
    path("move_equipment_to_maintenance/<int:equipment_id>/", views.move_equipment_to_maintenance, name="move_equipment_to_maintenance"),
    path("move_equipment_to_damaged_equipment/<int:equipment_id>/", views.move_equipment_to_damaged_equipment, name="move_equipment_to_damaged_equipment"),
    path("remove_equipment_from_mission/<int:equipment_id>/", views.remove_equipment_from_mission, name="remove_equipment_from_mission"),
    path("remove_equipment_from_maintenance/<int:equipment_id>/", views.remove_equipment_from_maintenance, name="remove_equipment_from_maintenance"),
    # Mga di ko pa magawa:
    path("from_mission_to_damaged_equipment/<int:equipment_id>/", views.from_mission_to_damaged_equipment, name="from_mission_to_damaged_equipment"),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

myapp/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# This is the database for Client: ####

class UserClassification(models.Model):
    # is_mechanic = models.BooleanField(default=False)
    # is_client = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(unique=True, null=True, blank=True)
    job = models.IntegerField(choices=[(1, 'User'), (2, 'Mechanic')], null=True, blank=True)

    def __str__(self):
        return self.user.username

class AllEquipment(models.Model):
    equipment_id = models.CharField(max_length=100, default='', blank=False)
    equipment_model = models.CharField(max_length=100, unique=True) 
    equipment_category = models.CharField(max_length=100, default='', blank=False) 
    equipment_name = models.CharField(max_length=100, default='', blank=False)
    equipment_description = models.CharField(max_length=250, default='', blank=False)

    def __str__(self):
        return self.equipment_name
    
class EquipmentOnMission(models.Model):
    all_equipment = models.ForeignKey(AllEquipment, on_delete=models.CASCADE)
    equipment_id_on_mission = models.CharField(max_length=100, default='', blank=False)
    equipment_model = models.CharField(max_length=100, default='', blank=False)
    equipment_category = models.CharField(max_length=100, default='', blank=False)
    equipment_name = models.CharField(max_length=100, default='', blank=False)
    equipment_description = models.CharField(max_length=250, default='', blank=False)

    def __str__(self):
        return self.equipment_model
    
class EquipmentOnMaintenance(models.Model):
    all_equipment = models.ForeignKey(AllEquipment, on_delete=models.CASCADE)
    equipment_id_on_maintenance = models.CharField(max_length=100, default='', blank=False)
    equipment_model = models.CharField(max_length=100, default='', blank=False)
    equipment_category = models.CharField(max_length=100, default='', blank=False)
    equipment_name = models.CharField(max_length=100, default='', blank=False)
    equipment_description = models.CharField(max_length=250, default='', blank=False)

    def __str__(self):
        return self.equipment_model

class DamagedEquipment(models.Model):
    all_equipment = models.ForeignKey(AllEquipment, on_delete=models.CASCADE)
    equipment_id_on_damaged = models.CharField(max_length=100, default='', blank=False)
    equipment_model = models.CharField(max_length=100, default='', blank=False)
    equipment_category = models.CharField(max_length=100, default='', blank=False)
    equipment_name = models.CharField(max_length=100, default='', blank=False)
    equipment_description = models.CharField(max_length=250, default='', blank=False)

    def __str__(self):
        return self.equipment_model
    
class ReturnedEquipment(models.Model):
    all_equipment = models.ForeignKey(AllEquipment, on_delete=models.CASCADE)
    equipment_id_on_returned = models.CharField(max_length=100, default='', blank=False)
    equipment_model = models.CharField(max_length=100, default='', blank=False)
    equipment_category = models.CharField(max_length=100, default='', blank=False)
    equipment_name = models.CharField(max_length=100, default='', blank=False)
    equipment_description = models.CharField(max_length=250, default='', blank=False)

    def __str__(self):
        return self.equipment_model
    

myapp/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserClassification, AllEquipment

class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class User:
            model = UserClassification
            fields = ['job',
                      'username',
                      'first_name', 
                      'last_name', 
                      'email',
                      'password1', 
                      'password2']

class EquipmentForm(forms.ModelForm):
    equipment_id = forms.CharField(required=True)
    equipment_model = forms.CharField(required=True)
    equipment_category = forms.CharField(required=True)
    equipment_name = forms.CharField(required=True)
    equipment_description = forms.CharField(required=True)

    class Meta:
        model = AllEquipment
        fields = ['equipment_id', 
                  'equipment_model', 
                  'equipment_category',
                  'equipment_name', 
                  'equipment_description']

myapp/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import RegistrationForm, EquipmentForm
from .models import UserClassification, AllEquipment, EquipmentOnMission, EquipmentOnMaintenance, DamagedEquipment

# Create your views here.

def home_page(request):
    return render(request, 'home.html')

def account(request):
    accounts = UserClassification.objects.all()
    return render(request, 'account.html', {'accounts': accounts})

def signup(request):
    if request.method == 'POST':
        user_form = RegistrationForm(request.POST)

        if user_form.is_valid():
            user_form.save()
            return redirect('home')
        else: 
            pass
    
    else: 
        user_form = RegistrationForm()

    return render(request, 'signup.html', {'user_form': user_form})

def client_signup(request):
    return render(request, 'client_signup.html')

def mechanic_signup(request):
    return render(request, 'mechanic_signup.html')

def add_equipment(request):
    if request.method == 'POST':
        equipment_form = EquipmentForm(request.POST)
        if equipment_form.is_valid():
            equipment_form.save()
            return redirect('home')
    else:
        equipment_form = EquipmentForm()

    return render(request, 'add_equipment.html', { 'equipment_form': equipment_form })

def all_equipment(request):
    all_equipment = AllEquipment.objects.all()
    return render(request, 'all_equipment.html', {'all_equipment': all_equipment})

def equipment_on_mission(request):
    equipment_on_mission = EquipmentOnMission.objects.all()
    return render(request, 'equipment_on_mission.html', {'equipment_on_mission': equipment_on_mission})

def equipment_on_maintenance(request):
    equipment_on_maintenance = EquipmentOnMaintenance.objects.all()
    return render(request, 'equipment_on_maintenance.html', {'equipment_on_maintenance': equipment_on_maintenance})

def damaged_equipment(request):
    damaged_equipment = DamagedEquipment.objects.all()
    return render(request, 'damaged_equipment.html', {'damaged_equipment': damaged_equipment})

# Try
def deploy_equipment_on_mission(request, equipment_id):
    equipment = get_object_or_404(AllEquipment, id=equipment_id)
    EquipmentOnMission.objects.create(
        all_equipment=equipment,
        equipment_id_on_mission=equipment.equipment_id,
        equipment_model=equipment.equipment_model,
        equipment_category=equipment.equipment_category,
        equipment_name=equipment.equipment_name,
        equipment_description=equipment.equipment_description,
    )
    return redirect('all_equipment')

# HIRAP!
# def move_equipment_to_maintenance(request, equipment_id):
#     if request.method == 'POST':
#         equipment_form = EquipmentOnMaintenance(request.POST)
#         if equipment_form.is_valid():
#             equipment_form.save()
#             equipment = get_object_or_404(AllEquipment, id=equipment_id)
#         EquipmentOnMaintenance.objects.create(
#             all_equipment=equipment,
#             equipment_id_on_maintenance=equipment.equipment_id,
#             equipment_model=equipment.equipment_model,
#             equipment_category=equipment.equipment_category,
#             equipment_name=equipment.equipment_name,
#             equipment_description=equipment.equipment_description,
#         )
#     else:
#         equipment_form = EquipmentOnMaintenance()

#     return render(request, 'all_equipment.html', { 'equipment_form': equipment_form })

def move_equipment_to_maintenance(request, equipment_id):
    equipment = get_object_or_404(AllEquipment, id=equipment_id)
    EquipmentOnMaintenance.objects.create(
        all_equipment=equipment,
        equipment_id_on_maintenance=equipment.equipment_id,
        equipment_model=equipment.equipment_model,
        equipment_category=equipment.equipment_category,
        equipment_name=equipment.equipment_name,
        equipment_description=equipment.equipment_description,
    )
    return redirect('all_equipment')

def move_equipment_to_damaged_equipment(request, equipment_id):
    equipment = get_object_or_404(AllEquipment, id=equipment_id)
    DamagedEquipment.objects.create(
        all_equipment=equipment,
        equipment_id_on_damaged=equipment.equipment_id,
        equipment_model=equipment.equipment_model,
        equipment_category=equipment.equipment_category,
        equipment_name=equipment.equipment_name,
        equipment_description=equipment.equipment_description,
    )
    return redirect('all_equipment')

def remove_equipment_from_mission(request, equipment_id):
    equipment = get_object_or_404(AllEquipment, id=equipment_id)
    on_mission_equipment_instance = EquipmentOnMission.objects.filter(
        all_equipment=equipment,
        equipment_id_on_mission=equipment.equipment_id,
        equipment_model=equipment.equipment_model,
        equipment_category=equipment.equipment_category,
        equipment_name=equipment.equipment_name,
        equipment_description=equipment.equipment_description,
    ).first()

    if on_mission_equipment_instance:
        on_mission_equipment_instance.delete()
    
    return redirect('all_equipment')

def remove_equipment_from_maintenance(request, equipment_id):
    equipment = get_object_or_404(AllEquipment, id=equipment_id)
    on_maintenance_equipment_instance = EquipmentOnMaintenance.objects.filter(
        all_equipment=equipment,
        equipment_id_on_maintenance=equipment.equipment_id,
        equipment_model=equipment.equipment_model,
        equipment_category=equipment.equipment_category,
        equipment_name=equipment.equipment_name,
        equipment_description=equipment.equipment_description,
    ).first()

    if on_maintenance_equipment_instance:
        on_maintenance_equipment_instance.delete()
    
    return redirect('all_equipment')

# DI PA OKAY!
def from_mission_to_damaged_equipment(request, equipment_id):
    if request.method == "POST":
        equipment = get_object_or_404(EquipmentOnMission, id=equipment_id)
        DamagedEquipment.objects.create(
            all_equipment=equipment.all_equipment,
            equipment_id_on_damaged=equipment.equipment_id_on_mission,
            equipment_model=equipment.equipment_model,
            equipment_category=equipment.equipment_category,
            equipment_name=equipment.equipment_name,
            equipment_description=equipment.equipment_description,
        )

        if equipment:
            equipment.delete()

        return redirect('all_equipment')

# def move_equipment(request):
#     if request.method == 'POST':
#         equipment_id = request.POST.get('equipment_id')
#         try:
#             equipment = AllEquipment.objects.get(id=equipment_id)
#             # Create an instance of EquipmentOnMission and save it
#             EquipmentOnMission.objects.create(
#                 equipment=equipment,
#                 equipment_model=equipment.equipment_model,
#                 equipment_name=equipment.equipment_name,
#                 equipment_description=equipment.equipment_description
#             )
#             return HttpResponse("Successfully moved equipment to EquipmentOnMission")
#         except AllEquipment.DoesNotExist:
#             return HttpResponse("Equipment does not exist")

#     equipment_list = AllEquipment.objects.all()
#     return render(request, 'move_equipment.html', {'equipment_list': equipment_list})

myapp/main/templates/account.html
<!DOCTYPE html>
<html>
    <head>
        <title>Accounts</title>
    </head>
    <body>
        <h1>Accounts</h1>
        {% for account in accounts %}
            <div>
                <p>{{ account.name }}</p>
                <p>{{ account.job }}</p>
                <p>{{ account.username }}</p>
                <p>{{ account.first_name }}</p>
                <p>{{ account.last_name }}</p>
                <p>{{ account.email }}</p>
            </div>
        {% endfor %}
    </body>
</html>

myapp/main/templates/add_equipment.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <section id="Equipment">
            <form method="post" action="{% url 'add_equipment' %}">
                {% csrf_token %}

                <div class="equipment-id">
                    {{ equipment_form.equipment_id.label }}
                    {{ equipment_form.equipment_id }}
                </div>
                
                <div class="equipment-model">
                    {{ equipment_form.equipment_model.label }}
                    {{ equipment_form.equipment_model }}
                </div>

                <div class="equipment-category">
                    {{ equipment_form.equipment_category.label }}
                    {{ equipment_form.equipment_category }}
                </div>

                <div class="equipment-name">
                    {{ equipment_form.equipment_name.label }}
                    {{ equipment_form.equipment_name }}
                </div>

                <div class="equipment-description">
                    {{ equipment_form.equipment_description.label }}
                    {{ equipment_form.equipment_description }}
                </div>

                <div class="add-equipment">
                    <button type="submit">Add Equipment</button>
                </div>
            </form>
        </section>
    </body>
</html>

myapp/main/templates/all_equipment.html
<!DOCTYPE html>
<html>
    <head>
        <title>All Equipment</title>
    </head>
    <body>
        <a href="{% url 'add_equipment' %}">
            Add Equipment
        </a>
        {% for equipment in all_equipment %}
        <div>
            <p>{{ equipment.equipment_id }}</p>
            <p>{{ equipment.equipment_model }}</p>
            <p>{{ equipment.equipment_category }}</p> 
            <p>{{ equipment.equipment_name }}</p> 
            <p>{{ equipment.equipment_description }}</p>
            {% if not equipment.equipmentonmission_set.exists and not equipment.damagedequipment_set.exists and not equipment.equipmentonmaintenance_set.exists %}
            <p>Status: Available</p>
            <form method="post" action="{% url 'deploy_equipment_on_mission' equipment.id %}">
                {% csrf_token %}
                <button type="submit">Deploy in Mission</button>
            </form>
            <form method="post" action="{% url 'move_equipment_to_maintenance' equipment.id %}">
                {% csrf_token %}
                <button type="submit">Move in Maintenance</button>
            </form>
            <form method="post" action="{% url 'move_equipment_to_damaged_equipment' equipment.id %}">
                {% csrf_token %}
                <button type="submit">Move in Damaged Equipment</button>
            </form>
            {% elif equipment.equipmentonmission_set.exists %}
                {% if equipment.damagedequipment_set.exists and equipment.equipmentonmission_set.exists %}
                    <p>Status: Broken</p>
                {% elif equipment.equipmentonmission_set.exists %}
                    <p>Status: On Mission</p>
                {% endif %}
            {% elif equipment.equipmentonmaintenance_set.exists %}
                <p>Status: Under Maintenance</p>
            {% elif equipment.damagedequipment_set.exists %}
                <p>Status: Broken</p>
            {% endif %}
        </div>
        {% endfor %}
    </body>
</html>

myapp/main/templates/available_equipment.html
<!DOCTYPE html>
<html>
    <head>
        <title>Available Equipment</title>
    </head>
    <body>
        {% for equipment in equipments %}
        <div>
            <p>{{ equipment.equipment_id }}</p>
            <p>{{ equipment.equipment_model }}</p>
            <p>{{ equipment.equipment_name }}</p> 
            <p>{{ equipment.equipment_description }}</p>
        </div>
        {% endfor %}
    </body>
</html>

myapp/main/templates/client_signup.html
<!DOCTYPE html>
<html>
    <head>
        <title>Client Signup</title>
    </head>
    <body>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"> Client Sign Up</button>
        </form>
    </body>
</html>

myapp/main/templates/damaged_equipment.html
<!DOCTYPE html>
<html>
    <head>
        <title>Equipment on Mission</title>
    </head>
    <body>
        {% for equipment in damaged_equipment %}
        <div>
            <p>{{ equipment.equipment_id_on_damaged }}</p>
            <p>{{ equipment.equipment_model }}</p>
            <p>{{ equipment.equipment_category }}</p>
            <p>{{ equipment.equipment_name }}</p> 
            <p>{{ equipment.equipment_description }}</p>
        </div>
        {% endfor %}
    </body>
</html>

myapp/main/templates/equipment_on_maintenance.html
<!DOCTYPE html>
<html>
    <head>
        <title>Equipment on Maintenance</title>
    </head>
    <body>
        {% for equipment in equipment_on_maintenance %}
        <div>
            <p>{{ equipment.equipment_id_on_maintenance }}</p>
            <p>{{ equipment.equipment_model }}</p>
            <p>{{ equipment.equipment_category }}</p>
            <p>{{ equipment.equipment_name }}</p> 
            <p>{{ equipment.equipment_description }}</p>
            <form method="post" action="{% url 'remove_equipment_from_maintenance' equipment.all_equipment.id %}">
                {% csrf_token %}
                <button type="submit">Remove from Maintenance</button>
            </form>
        </div>
        {% endfor %}
    </body>
</html>

myapp/main/templates/equipment_on_mission.html
<!DOCTYPE html>
<html>
    <head>
        <title>Equipment on Mission</title>
    </head>
    <body>
        {% for equipment in equipment_on_mission %}
        <div>
            <p>{{ equipment.equipment_id_on_mission }}</p>
            <p>{{ equipment.equipment_model }}</p>
            <p>{{ equipment.equipment_category }}</p>
            <p>{{ equipment.equipment_name }}</p> 
            <p>{{ equipment.equipment_description }}</p>
            <form method="post" action="{% url 'remove_equipment_from_mission' equipment.id %}">
                {% csrf_token %}
                <button type="submit">Remove from Mission</button>
            </form>
            <form method="post" action="{% url 'from_mission_to_damaged_equipment' equipment.id %}">
                {% csrf_token %}
                <button type="submit">Move in Damaged Equipment</button>
            </form>
        </div>
        {% endfor %}
    </body>
</html>

myapp/main/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <title>Home</title>
    </head>
    <body>
        <div>
            <div>
                <a href="{% url 'all_equipment' %}"><button>View All Equipment</button></a>
                <a href="{% url 'equipment_on_mission' %}"><button>View All Equipment On Mission</button></a>
                <a href="{% url 'equipment_on_maintenance' %}"><button>View All Equipment On Maintenance</button></a>
                <a href="{% url 'damaged_equipment' %}"><button>View All Damaged Equipment</button></a>
            </div>
        </div>
    </body>
</html>

myapp/main/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <h1>Hi!</h1>
    </body>
</html>

myapp/main/templates/mechanic_signup.html
<!DOCTYPE html>
<html>
    <head>
        <title>Mechanic Signup</title>
    </head>
    <body>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Mechanic Sign Up</button>
        </form>
    </body>
</html>

myapp/main/templates/move_equipment.html
<!DOCTYPE html>
<html>
<head>
    <title>Move Equipment</title>
</head>
<body>
    <h1>Move Equipment</h1>
    <form method="post">
        {% csrf_token %}
        <label for="equipment_id">Select Equipment to Move:</label>
        <select name="equipment_id" id="equipment_id">
            {% for equipment in equipment_list %}
                <option value="{{ equipment.id }}">{{ equipment.equipment_name }}</option>
            {% endfor %}
        </select>
        <button type="submit">Move</button>
    </form>
</body>
</html>

myapp/main/templates/signup.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <section id="Signup">

            <form method="post" action="{% url 'signup' %}">
                {% csrf_token %}

                <label for="status">Job: </label>
                <select name="job" id="status">
                    <option value="1">User</option>
                    <option value="2">Mechanic</option>
                </select>

                <div class="username">
                    {{ user_form.username.label }}
                    {{ user_form.username }}
                </div>
                
                <div class="fname">
                    {{ user_form.first_name.label }}
                    {{ user_form.first_name }}
                </div>

                <div class="lname">
                    {{ user_form.last_name.label }}
                    {{ user_form.last_name }}
                </div>

                <div class="email">
                    {{ user_form.email.label }}
                    {{ user_form.email }}
                </div>

                <div class="password1">
                    {{ user_form.password1.label }}
                    {{ user_form.password1 }}
                </div>

                <div class="password2">
                    {{ user_form.password2.label }}
                    {{ user_form.password2 }}
                </div>

                <div class="signup">
                    <button type="submit">Sign Up</button>
                </div>

            </form>

        </section>
        <h1>Hi!</h1>
    </body>
</html>